### PR TITLE
bprm rebase

### PR DESCRIPTION
**Pull request by backslashxx**

### CODE REVIEW

**Comment by selfmusing** [comment]
@backslashxx 

I'm getting this after updating the security hooks to v1.3 and btw I've already picked all those new changes which was needed for bprm_checks support : 

```
CC      fs/configfs/inode.o
../security/security.c:343:2: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  343 |         ksu_bprm_check(bprm);
      |         ^
      |         int
../security/security.c:343:17: error: a parameter list without types is only allowed in a function definition
  343 |         ksu_bprm_check(bprm);
      |                        ^
../security/security.c:651:20: error: use of undeclared identifier 'old_dentry'
  651 |         ksu_handle_rename(old_dentry, new_dentry);
      |                           ^
../security/security.c:651:32: error: use of undeclared identifier 'new_dentry'
  651 |         ksu_handle_rename(old_dentry, new_dentry);
      |                                       ^
../security/security.c:1028:2: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
 1028 |         ksu_handle_setuid(new, old);
      |         ^
      |         int
../security/security.c:1028:20: error: a parameter list without types is only allowed in a function definition
 1028 |         ksu_handle_setuid(new, old);
      |                           ^
../security/security.c:1105:19: error: use of undeclared identifier 'option'
 1105 |         ksu_handle_prctl(option, arg2, arg3, arg4, arg5);
      |                          ^
../security/security.c:1105:27: error: use of undeclared identifier 'arg2'
 1105 |         ksu_handle_prctl(option, arg2, arg3, arg4, arg5);
      |                                  ^
../security/security.c:1105:33: error: use of undeclared identifier 'arg3'
 1105 |         ksu_handle_prctl(option, arg2, arg3, arg4, arg5);
      |                                        ^
../security/security.c:1105:39: error: use of undeclared identifier 'arg4'
 1105 |         ksu_handle_prctl(option, arg2, arg3, arg4, arg5);
      |                                              ^
../security/security.c:1105:45: error: use of undeclared identifier 'arg5'
 1105 |         ksu_handle_prctl(option, arg2, arg3, arg4, arg5);
      |                                                    ^
11 errors generated.
make[2]: *** [../scripts/Makefile.build:365: security/security.o] Error 1
make[1]: *** [/home/runner/work/perf_kernel/perf_kernel/Perf/Makefile:1239: security] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by backslashxx** [comment]
clearly syntax error (go and define ksu_bprm_check as int) 

also this want a real pr, this is an accident

if you really want to migrate _ksud to bprm LSM, its on my repo, its a patch series

<details>
  <summary>show</summary>

image

</details>

mind you this change is a bit huge, so you either just use my repo or fix your issues yourself.

**Comment by selfmusing** [comment]
> clearly syntax error (go and define ksu_bprm_check as int)
> 
> also this want a real pr, this is an accident
> 
> if you really want to migrate _ksud to bprm LSM, its on my repo, its a patch series
> 
> show
> mind you this change is a bit huge, so you either just use my repo or fix your issues yourself.

Actually , I just wanted to try the new ksu hooks v1.5 & security hooks v1.3 with commonized ksud execv , alongside that lsm dvpts hooks thing.
Does It also need to add ksu_bprm or ksu_sbmount changes on my ksu repo 🤔 ?

**Comment by backslashxx** [comment]
actually, since theres a lot of changes, just pick everything
I'll re-bisect properly once ksu itself tags a release

**Comment by selfmusing** [comment]
> actually, since theres a lot of changes, just pick everything I'll re-bisect properly once ksu itself tags a release

I thought  your hooks guide will just work fine without needing to pick everything , but later I realised a lot of things are mixed up together to work so I can't just choose any changes specifically without breaking stuff 💔🥀

**Comment by backslashxx** [comment]
lets just talk about this on my repo @selfmusing

**Comment by selfmusing** [comment]
> lets just talk about this on my repo @selfmusing

Screenshot_20250623-150344_Chrome
