### ISSUE TITLE
[3.2.2] GKI compilation failed

### ISSUE THREAD

**Issue by LFRon** [tiann/KernelSU#3356]
### Please check before submitting an issue

- [x] I have searched the issues and haven't found anything relevant
- [x] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [x] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I have met compilation error while compiling GKI kernel, but works on KernelSU 3.2.1

In file included from ../drivers/kernelsu/core/init.c:10:
../drivers/kernelsu/policy/allowlist.h:6:10: fatal error: 'uapi/app_profile.h' file not found
    6 | #include "uapi/app_profile.h"
      |          ^~~~~~~~~~~~~~~~~~~~
  CC [M]  drivers/nvmem/qcom-spmi-sdam.o                                                                                                         
  CC [M]  drivers/power/oplus/v1/charger_ic/oplus_battery_sm8550.o
1 error generated.
make[3]: *** [../scripts/Makefile.build:295: drivers/kernelsu/core/init.o] Error 1
make[2]: *** [../scripts/Makefile.build:564: drivers/kernelsu] Error 2
make[2]: *** Waiting for unfinished jobs....

### Device info

- Device: OnePlus Ace 3 (Not 12R)
- OS Version: LineageOS 23.2
- KernelSU Version: 3.2.2
- Kernel Version: 5.15.200 (Link at: https://github.com/LineageOS/android_kernel_oneplus_sm8550)

**Comment by SaleOff** [comment]
https://github.com/tiann/KernelSU/commit/95a31f28c875b006d59bde0c768e92d4363a2c7a
Close issue
