### ISSUE TITLE
Failed Compilation for 4.4 kernel

### ISSUE THREAD

**Issue by GhostMaster69-dev** [tiann/KernelSU#1720]
Failed to compile with latest changes on 4.4 kernel with following error:

../drivers/kernelsu/kernel/sucompat.c:331:40: error: use of undeclared identifier 'real_regs'
  331 |         inode = (struct inode *)PT_REGS_PARM1(real_regs);
      |                                               ^
1 error generated.
