### ISSUE TITLE
Kernel compilation fails due to commit c0066b6

### ISSUE THREAD

**Issue by keremgokcek** [tiann/KernelSU#706]
**Describe the bug**
The commit c0066b68f54ce1704bbbb15c58c747bd94aafd00 is causing the kernel build to fail.

**Expected behavior**
The kernel should compile successfully.

**Smartphone:**
 - Device: Xiaomi Mi Note 10
 - OS: Android 13 (Linux 4.14.319)
 - Version: v0.6.1 (11073)

Error message:
```
../drivers/kernelsu/kernel_compat.c:53:72: error: use of undeclared identifier 'init_task'
    if (current->nsproxy && current->fs && current->nsproxy->mnt_ns != init_task.nsproxy->mnt_ns) {
                                                                       ^
../drivers/kernelsu/kernel_compat.c:55:122: error: use of undeclared identifier 'init_task'
        pr_info("android contex saved enabled due to init mnt_ns(%p) != android mnt_ns(%p)\n", current->nsproxy->mnt_ns, init_task.nsproxy->mnt_ns);
                                                                                                                         ^
2 errors generated.
```
When I add #include "linux/init_task.h" to the beginning of the KernelSU/kernel/kernel_compat.c file, the compilation completes without errors.
