### ISSUE TITLE
Compilation error caused by #563 submission

### ISSUE THREAD

**Issue by Coconutat** [tiann/KernelSU#657]
关于提交：
[#563](https://github.com/tiann/KernelSU/commit/bd8434f4f4f3e631f66d36ad8afdf7a4201c4851)  
虽然优化性能但是降低了兼容性。
部分老旧内核不能很好适配。
比如不兼容__maybe_unused参数，
按照新的非GKI修改的代码去集成教程去修改也不能很好适配这个提交的内容。
会出现这样的错误：

`
`drivers/built-in.o: In function `input_handle_event':
out/../drivers/input/input.c:378: undefined reference to `ksu_input_hook'
out/../drivers/input/input.c:378: undefined reference to `ksu_input_hook'
out/../drivers/input/input.c:378: undefined reference to `ksu_input_hook'
out/../drivers/input/input.c:378: undefined reference to `ksu_input_hook'
out/../drivers/input/input.c:378: undefined reference to `ksu_input_hook'
drivers/built-in.o:out/../drivers/input/input.c:378: more undefined references to `ksu_input_hook' follow
fs/built-in.o: In function `vfs_read':
out/../fs/read_write.c:494: undefined reference to `ksu_vfs_read_hook'
out/../fs/read_write.c:494: undefined reference to `ksu_vfs_read_hook'
fs/built-in.o: In function `do_execveat_common':
out/../fs/exec.c:1698: undefined reference to `ksu_execveat_hook'
out/../fs/exec.c:1698: undefined reference to `ksu_execveat_hook'
make[1]: *** [Makefile:1195：vmlinux] 错误 1'
`

我认为应该把老的版本的手动修改作为一种兼容性适配，能让二者可选。

**Comment by tiann** [comment]
You should take a closer look at the updated document, these compilation issues should be easy to fix.
